apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-app-deployment
  labels:
    app: churn-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-app
  template:
    metadata:
      labels:
        app: churn-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: churn-app
          image: registry.gitlab.com/swasifmurtaza/churn-prediction-ml:latest
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          # Removed volumeMounts here
      imagePullSecrets:
        - name: gitlab-regcred
      # Removed volumes here
