{
 "title": "Customer Churn API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "API Request Latency (P95)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_request_duration_seconds_bucket{job=\\\"kubernetes-pods\\\"}[5m])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}} P95"
    }
   ]
  },
  {
   "title": "API Request Rate (Success vs Error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{status_code=~\"2..\", job=\\\"kubernetes-pods\\\"}[1m])) by (method, path)",
     "legendFormat": "{{method}} {{path}} - Success"
    },
    {
     "expr": "sum(rate(starlette_responses_total{status_code=~\"[45]..\", job=\\\"kubernetes-pods\\\"}[1m])) by (method, path)",
     "legendFormat": "{{method}} {{path}} - Error"
    }
   ]
  },
  {
   "title": "HTTP Status Codes Count (5m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(starlette_requests_total{job=\\\"kubernetes-pods\\\"}[5m])) by (status_code)",
     "legendFormat": "status {{status_code}}"
    }
   ]
  }
 ]
}