apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
         
  # type: LoadBalancer # If you want to expose Prometheus externally (consider security)
  # type: NodePort # Or NodePort for external access via node IP and a specific port
  # Typically Prometheus is accessed internally by Grafana